In [15]:
import tensorflow_hub as hub
import numpy as np

In [8]:
model = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [9]:
def embed(input):
  return model(input)

In [10]:
def run_and_plot(messages_):
  message_embeddings_ = embed(messages_)
  plot_similarity(messages_, message_embeddings_, 90)

In [29]:
messages = [
    "is priyanshu at home",
    "where is priyanshu","is priyanshu home"]

In [30]:
message_embeddings = embed(messages)

In [31]:
message_embeddings

<tf.Tensor: id=10610, shape=(3, 512), dtype=float32, numpy=
array([[-0.04003221, -0.01225166, -0.02857817, ..., -0.03092518,
         0.06319692, -0.04786884],
       [-0.07753084,  0.05779301,  0.02744647, ...,  0.02034679,
         0.03773318, -0.02430033],
       [-0.02325683, -0.01581812,  0.01705606, ..., -0.07389687,
         0.07736799, -0.02980059]], dtype=float32)>

In [32]:
np.inner(message_embeddings, message_embeddings)

array([[0.9999999 , 0.33662224, 0.81837815],
       [0.33662224, 0.99999976, 0.35016462],
       [0.81837815, 0.35016462, 0.9999993 ]], dtype=float32)

In [2]:

embeddings = embed([
    "The quick brown fox jumps over the lazy dog.",
    "I am a sentence for which I would like to get its embedding"])

print(embeddings)

tf.Tensor(
[[-0.03133017 -0.06338635 -0.01607501 ... -0.0324278  -0.04575742
   0.05370458]
 [ 0.05080862 -0.01652429  0.01573782 ...  0.0097666   0.03170121
   0.01788118]], shape=(2, 512), dtype=float32)


In [ ]:
cosine_similarity = 1 - spatial.distance.cosine(vector1, vector2)